/**
 * This class is generated by jOOQ
 */
package tech.codingclub.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongsRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.tables.records.SongsRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 2007182224;

	/**
	 * Setter for <code>public.songs.songName</code>.
	 */
	public void setSongname(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.songs.songName</code>.
	 */
	public java.lang.String getSongname() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.songs.duration</code>.
	 */
	public void setDuration(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.songs.duration</code>.
	 */
	public java.lang.String getDuration() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.songs.singers</code>.
	 */
	public void setSingers(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.songs.singers</code>.
	 */
	public java.lang.String getSingers() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.songs.musicDirector</code>.
	 */
	public void setMusicdirector(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.songs.musicDirector</code>.
	 */
	public java.lang.String getMusicdirector() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.songs.lyricist</code>.
	 */
	public void setLyricist(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.songs.lyricist</code>.
	 */
	public java.lang.String getLyricist() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.tables.Songs.SONGS.SONGNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.tables.Songs.SONGS.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.tables.Songs.SONGS.SINGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.tables.Songs.SONGS.MUSICDIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.tables.Songs.SONGS.LYRICIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSongname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSingers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMusicdirector();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLyricist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value1(java.lang.String value) {
		setSongname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value2(java.lang.String value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value3(java.lang.String value) {
		setSingers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value4(java.lang.String value) {
		setMusicdirector(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value5(java.lang.String value) {
		setLyricist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongsRecord
	 */
	public SongsRecord() {
		super(tech.codingclub.tables.Songs.SONGS);
	}

	/**
	 * Create a detached, initialised SongsRecord
	 */
	public SongsRecord(java.lang.String songname, java.lang.String duration, java.lang.String singers, java.lang.String musicdirector, java.lang.String lyricist) {
		super(tech.codingclub.tables.Songs.SONGS);

		setValue(0, songname);
		setValue(1, duration);
		setValue(2, singers);
		setValue(3, musicdirector);
		setValue(4, lyricist);
	}
}
